### ISSUE TITLE
GameObjects with label icons appear improperly in list

### ISSUE THREAD

**Issue by vertxxyz** [sabresaurus/Sidekick#49]
![image](https://user-images.githubusercontent.com/21963717/124892250-0eafae80-e01d-11eb-8f26-6871effb8805.png)

**Comment by sabresaurus** [comment]
![image](https://user-images.githubusercontent.com/17784523/129453499-face5ac0-3087-42c2-894a-08bed3dd0993.png)
Fixed by making them square, inspired by https://github.com/neon-age/Smart-Hierarchy
